services:
  api-service:
    build: ./backend
    # es necesario exponer los puertos ya que el objetivo de la actividad es monitorear el trafico de red TCP y UDP crudos.
    ports:
      - "12000:12000/tcp" 
      - "12001:12001/udp"
    networks:
      - dokploy-network
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  dashboard:
    build: ./frontend
    networks:
      - dokploy-network
    restart: always

networks:
  dokploy-network:
    external: true